apiVersion: apps/v1
kind: Deployment
metadata:
  name: mscredit
  namespace: prod
  labels:
    app: mscredit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mscredit
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mscredit
    spec:
      containers:
        - image: mscredits-containers:9
          imagePullPolicy: Always
          name: mscredit
          ports:
            - containerPort: 8082
