---
apiVersion: v1
kind: Service
metadata:
  name: mscredit
  labels:
    k8s-app: mysql
    run: mysql
spec:
  type: NodePort
  ports:
    - port: 8082
      protocol: TCP
  selector:
    k8s-app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mscredit
  namespace: prod
  labels:
    k8s-app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: mysql
    spec:
      containers:
        - image: us.icr.io/ibmdigitalbank/mscredits-containers:9
          imagePullPolicy: Always
          name: mscredit
          ports:
            - containerPort: 8082
